version: '3.8'
services:
  db:
    image: mysql:5.7
    container_name: mysql-hotel
    restart: always
    environment:
       MYSQL_ROOT_PASSWORD: hotel123
       MYSQL_DATABASE: hotel_sustentavel
       MYSQL_USER: userhotel
       MYSQL_PASSWORD: hotelpass
    ports:
      - "3307:3306" 
    volumes:
      - db_data:/var/lib/mysql

  api:
    build: .
    container_name: api-hotel
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      MYSQL_HOST: db
      MYSQL_DATABASE: hotel_sustentavel
      MYSQL_USER: userhotel
      MYSQL_PASSWORD: hotelpass

volumes:
  db_data:
